MODULE COMMAND_ARGS  
  INTERFACE 
    FUNCTION IARGC()
!DEC$ ATTRIBUTES DEFAULT :: IARGC
      USE WINAPI_FD
      INTEGER(SINT) :: IARGC
    END FUNCTION

!	  SUBROUTINE GETARG(N, BUFFER, STATUS)
!!DEC$ ATTRIBUTES DEFAULT :: GETARG
!	    INTEGER(2) N
!	    CHARACTER*(*) BUFFER
!	    INTEGER(2), OPTIONAL :: STATUS      
!	  END SUBROUTINE

    SUBROUTINE GETARG(N, BUFFER)
!DEC$ ATTRIBUTES DEFAULT :: GETARG
      INTEGER(4) N
      CHARACTER*(*) BUFFER
    END SUBROUTINE
  END INTERFACE
END MODULE COMMAND_ARGS  

